dist: trusty
sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /^v?\d+\.\d+\.\d+/
install: true
script: docker login -u $ATOMIST_REPO_USER -p $ATOMIST_REPO_TOKEN $ATOMIST_DOCKER_REGISTRY
  && bash src/main/scripts/travis-build.bash
env:
  global:
  - secure: H+4UlKnmMiyCtGyGL2ZzFFIGRkmom4xPmMzfxHMrPofw5cMcgv6vUWMqEAIMuhYHRQT3Ey6ngcsTp/izlV7lKq5Cr/Ftrqpegd2rTE2Y5zMomxtRojX9NifHuwAfKWp0j5l23myK8Ps8/Wxp7BlLGs9ufrnEYlksxaMsCtyXfIe+4UNvvik6JMhIN/VIjbMMdN6zhJXuNUu6QopXOFApobumXmrp+DWC+hbW9GdRPP6VykzCCtZej6L/E3+Ak5FpwslQG1iAcxLYwPpt1pjU7QV1ETx/3CuG20HOLvU/jAkd+R5T/qzRu+LW8dIJVk4Pwcq9KeCu5H9I7MwCjejPynI8BAmTSbgoWI7l8JN95QyEgMUuno3S8DlUlPrUuaZLWCCPrLk3Jw5Xh7ek7BKQ6XF39FHHTEtCI6YzhIUJZw4NLYuWUTK33Y0yOtJI/pEYnTBiry8g8LZhHo4bAZlnCGQTPF456iCjQsavkDGCtWS8AmqKDmhfcCasCWLyLjGrhzq3Hw9qs23o3nk8tzQrK+Y+qO73c24kOt1Jje74XcfbwZDO39jeBV4vsEK7ODhAoMHOj8hw9Ac6pr8o+zlsPAoDdJACsj+VrJRwsLn9ygJ8V20/Th2V4wB8vdpeyl8w6E+G/oGTysmTmf4/neLpE34HHKT9kFKJfJBpSWZi9F8=
  - secure: KNlLWvLIQ5U2sOtDlP0eZDnfYf6GVtUzMikziYL8UYpN4lYHOsdwGnJxC+4mpIlwVdAsSbsHLtRjIHJPymsbKywFLKtOaceylXy7iBu0jTirPQnLslQdxiJ1JQxylTvzfcRljvA8E5h9zGMaWF5JwFq+VdeBJXB2U/3pNXxrCRW6PlYzDgBJmS4/gW4Y3xGzvKv+ATkcKqmDpdArFSUkizfA8NKYdqTPzfPYydZ7H2T0ebySeDqCRv9EP0h7zgjNs137A57cyp33q80MKGWv8V3RuYZ1xi3+4YvuufTQ9xyCnloTks2nNyZvpM5oJQq5CcVwl+0CdkSeGIpDqu9vm9O94EfDVnq+bAS8F0CCgtVNYK7Tyq1LgwkD1NG4kNwjGTgjIEDlEqgUsXehF8qlYWowSLXymN69eNiBTcuelXtoFwpsy3nHXmOtjvzmPbTu6/UYq6ZghYtG9kvgTDKtpDG0gWnMKVw4NaKJDxs3/wkSztI7nv1I+wgxeZAfR7HRcseqTLMNq6jj/F+oapTdT8Yd8Dp2yiu6tZjzBOHfFPIYV8l/8K2MTFESwryeBun3rs2LKlmlkaDc7x8KxVkbrErYWLT+Y5X+uxMtknoTfB7UDV4nYLyE4nUt82H5+PI6IUib8fjnJRSwUP1SpKiAP0Tv3cua4O+7sreSSYaFfSY=
  - secure: HT6EE4LeRlwpbnFMu0mgvK7vlrrUXkrW6NJvLz4at6N57euPLXMdqnggp1q10zdEcSP6u3bBGlCHw7+8wIaIN0Uphyi08B2+LXxgpswOwenaKbJQWxouD4E7MzV5htTdg0mzyQS+jrKXTnoZsYx7UQHRJvSl6+3OJHqTR9+Y6M4YkRsiIGeFgr2qd+8kUwOfZYoKM+L+q9YM+xKSAngccNUx5XNEy1sm5IpVmvmwCvZ6LFsv5ivlRROuUtL78UcpYk4nT4gOKCfVzf/mp0Jn08WJB4ROV8VJPbgKz+vUBHWHDo1YGphPg17z2FB0GT7hrgXxH64HUoX/qgeqgqob32OOgybj45L31BgDx7ThGgado8Uq8aCA29n47l+MkFbtWtFBzGkq/289DxZutAb80C7IuU/yCA363JJreWw70rIK21wabbCQKjl9mjXbeyWqg07XGWZS/X8Mv2U0QPSDLSHyxnhgEFQlnP5sM2p3ddevTRKQypB9K1XpSEQ3y1jUvsA5MNY2So/cnEQZp4iZ9Qc9u40n29uAzjlZrjruLn8h8bX0qrlPUmISecHn8WM0TC22bO83SL8M8Wso+P5cLQOKdVICdFrWjdXDC0b04Uxp5gsqmcP+nwS+liHES+K8Y+m/JaIjNA1pN8BedA7dv0yMkxQ2NQCzJYuSMyq50QU=
  - ATOMIST_DOCKER_REGISTRY=sforzando-docker-dockerv2-local.artifactoryonline.com
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
